---
- name: Install Python Pip
  apt: pkg=python-pip state=present update_cache=yes

- name: Install Beaver
  command: pip install beaver

- name: move initd for Beaver
  copy: src=beaver.init.d dest=/etc/init.d/beaver 

- name: register beaver init script
  command: update-rc.d beaver defaults

- name: create extract folder
  file: dest=/etc/beaver mode=640 owner=root group=root state=directory

- name: configure beaver
  template: src=beaver.conf.j2 dest=/etc/beaver/conf mode=0644
  notify:
    - Restart Beaver

