---
- name: download elasticsearch
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb dest=/tmp/elasticsearch.deb mode=0644

- name: Install OpenJDK7
  apt: pkg=default-jre-headless state=present update_cache=yes

- name: Copy mount script over
  copy: src=mount_ec2_volumes.sh dest=/tmp/mount_ec2_volumes.sh owner=root group=root mode=744

- name: Mount Volumes
  command: chdir=/tmp creates=/data/volumes ./mount_ec2_volumes.sh 

- name: Install ElasticSearch
  command: dpkg -i /tmp/elasticsearch.deb creates=/etc/elasticsearch

- name: Configure ElasticSearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0644
  notify:
    - Restart ElasticSearch

- name: Install Elasticsearch Plugins
  command: "{{ elasticsearch_base_dir }}/bin/plugin -install {{ item }}"
  with_items: 
    - "{{ plugin_install }}"

- name: Enable ElasticSearch service
  service: name=elasticsearch enabled=yes state=started
