---
- name: download elasticsearch
  get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb dest=/tmp/elasticsearch.deb mode=0644

- name: Install OpenJDK7
  apt: pkg=default-jre-headless state=present update_cache=yes

- name: Install ElasticSearch
  command: dpkg -i /tmp/elasticsearch.deb creates=/etc/elasticsearch

- name: Configure ElasticSearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml mode=0644
  notify:
    - Restart ElasticSearch

- name: Enable ElasticSearch service
  service: name=elasticsearch enabled=yes state=started